### ISSUE TITLE
Crash with Electron 12.0.0 on Windows

### ISSUE THREAD

**Issue by RSATom** [RSATom/WebChimera.js#141]
https://github.com/RSATom/WebChimera.js/issues/134#issuecomment-822749602
> I was not able to get https://github.com/RSATom/wcjs-ugly-demo working with Electron 12.0.0 and WebChimera v0.3.1b on Windows. Electron would crash and show an empty all white screen with no error message. Reverting to Electron 11.1.0 and WebChimera v0.3.1 works.
Can you look into fixing this for the latest Electron?

**Comment by RSATom** [comment]
Was able to reproduce... Now need to find some time to debug and fix...

**Comment by RSATom** [comment]
@mattzucker should be fixed now, please check.

**Comment by mattzucker** [comment]
It's still crashing for me using the 0.5.0 version and Electron 12.0.6.  I had to build the Windows binaries myself, so maybe I did something wrong.
package.json
```
"devDependencies": {
    "electron": "12.0.6",
    "electron-builder": "^22.10.5"
  },
  "dependencies": {
    "webchimera.js": "^0.5.0",
    "webgl-video-renderer": ">=0.2.0"
  }
```
I ran
```
npm install --ignore-scripts
cd node_modules\webchimera.js
build_electron.cmd
```

I got some warnings, but the build completed successfully.  When I try to open a video the whole thing crashes and Electron shows an empty screen.

**Comment by RSATom** [comment]
Does https://github.com/RSATom/wcjs-ugly-demo works for you?

**Comment by RSATom** [comment]
Also, what Visual Studio version do you use?

**Comment by RSATom** [comment]
@mattzucker Can you please try `wcjs-ugly-demo` with [prebuilt binaries](https://github.com/RSATom/WebChimera.js/releases/tag/v0.5.0)

**Comment by mattzucker** [comment]
Same result, Electron crashes with no helpful messages.  I started over with a new git clone of wcjs-ugly-demo just in case, but that didn't help.

**Comment by dbussert** [comment]
Crashes for me as well with the latest (and all 12.x version). I'm using `wcjs-ugly-demo` to test, both with prebuilt and converted to use `wcjs-prebuilt`. With `wcjs-prebuilt` I added this to package.json

```
	"wcjs-prebuilt": {
		"runtime": "electron",
		"runtimeVersion": "v12.0.7",
		"version": "v0.5.0"
	},
```

Result is white screen and no dev tools 
![image](https://user-images.githubusercontent.com/2479487/118043915-fdf7fa80-b343-11eb-8bfc-689901cdc137.png)

**Comment by RSATom** [comment]
@mattzucker @dbussert please try the latest version

**Comment by dbussert** [comment]
That fixed it for me
