### ISSUE TITLE
[Linux] Video playback broken with Electron 0.36.8+

### ISSUE THREAD

**Issue by asherkin** [RSATom/WebChimera.js#69]
`onFrameSetup` is called fine, `onFrameReady` is never called.

I'm thinking this is probably a Linux-only issue, and possibly related to "Don't drop capabilities in renderer process." from the Electron changelog - since VLC (well, I think avcodec actually) is also now logging `detected 4 logical cores`. I'm guessing multithreaded software decoding is going awry somewhere.
##

**Comment by RSATom** [comment]
What VLC version do you use?

**Comment by asherkin** [comment]
Got a couple of patches (unrelated to anything important - just HLS bandwidth selection tweaks) on top of the tagged 2.2.2 release.
Nothing was changed other than the electron version when bisecting it back to 0.36.8.

**Comment by RSATom** [comment]
Thanks, I'll look.

**Comment by RSATom** [comment]
checked on Windows with Electron 0.36.9 - it works fine... so it could be really linux specific...

btw, why do you need 0.36.9?

**Comment by asherkin** [comment]
I'm after `BrowserWindow.getNativeWindowHandle`, but there are quite a few
other nice-to-haves (like the premature remote object freeing, which I'm
running into quite a lot) - generally I like to stay as current as possible
anyway, it makes reporting issues easier.

**Comment by RSATom** [comment]
> I'm after `BrowserWindow.getNativeWindowHandle`

Does it mean it's possible now place custom windows on Electron main window? Maybe I should resurrect `WebChimera` plugin...

**Comment by Ivshti** [comment]
Hm...that one is new... @RSATom if a window handle is all you need, then please consider doing something with it!

Do you think it's possible, if you get a window handle to a transparent Electron window, to draw a video via VLC, or even better - MPV - in it's background?

**Comment by RSATom** [comment]
Yes, I can, but unfortunately not in background. I.e. don't think it will be possible place any html elements over it. That's why I'm thinking about `WebChimera`, i.e. some video engine + QML for UI.

**Comment by RSATom** [comment]
Something very strange happening. I can't play .avi on Linux with Electron 0.36.9. 
```
[0000169ee8958518] core decoder error: Codec `mp4v' (MPEG-4 Video) is not supported.
[0000169ee8958518] core decoder error: Codec not supported
[0000169ee8958518] core decoder error: VLC could not decode the format "mp4v" (MPEG-4 Video)
```

the same file plays fine in  NW.js

**Comment by asherkin** [comment]
And the plot thickens...

With `v0.37.2`, most things work fine - but any media requiring libavcodec for decoding crashes inside Electron's `libffmpeg.so` (testing with a H.264 / AAC M2TS stream). If I replace `libffmpeg.so` with the one Electron provides without propriety codecs (so no H.264), no crash and audio plays fine, but obviously no video.

It is quite the mystery.

Crash dump: https://gist.github.com/asherkin/9f805d8adfbdde5034a4
(it it would actually be useful, I could gather the relevant libvlc symbols as well)

**Comment by RSATom** [comment]
Don't think I can do something with it.

**Comment by jayke-vbh** [comment]
Hi guys,

Is there any news on this issue? I'm seeing the exact same thing with Electron/WebChimera.js(specifically wcjs-player) on Linux (Debian 8.0). Any version of Electron < 0.36.8 is working fine, but newer versions do not show the video. In the console I get the error:

`[h264 @ 0x3c4f2cac4680] no frame!` (many times)

I would like to go to Electron v1.0.* because that fixes some other issues (no WebChimera.js related) I'm having, but this issue is preventing me from doing so.

Please let me know if I can do more to troubleshoot or find more information, happy to help tracking down the problem.

**Comment by RSATom** [comment]
@jayke-vbh, unfortunately still can't find enough time to find solution... sorry.  Will try to do something soon.

**Comment by asherkin** [comment]
My theory here is that the problem is caused by Electron's `libffmpeg.so` exporting symbols as global, which are being used in preference to the ones in the system's `libavcodec.so` (which are what VLC's `libavcodec_plugin.so` is expecting to get). I ran into a similar issue in another project I work on recently, which caused similarly confusing issues.

```
$ find . -type f -print0 | xargs -0 nm -AD 2>/dev/null | grep avcodec_default_get_format
./vlc/lib/vlc/plugins/codec/libavcodec_plugin.so:                 U avcodec_default_get_format
$ find /usr/lib64/ -type f -print0 | xargs -0 nm -AD 2>/dev/null | grep avcodec_default_get_format
/usr/lib64/libavcodec.so.56.26.100:0000000000418860 T avcodec_default_get_format
/usr/lib64/vlc/plugins/codec/libavcodec_plugin.so:                 U avcodec_default_get_format
$ find /usr/lib/node_modules/electron-prebuilt/dist/ -type f -print0 | xargs -0 nm -AD 2>/dev/null | grep avcodec_default_get_format
/usr/lib/node_modules/electron-prebuilt/dist/libffmpeg.so:000000000015edb0 T avcodec_default_get_format
```

Chromium is explicitly building without `-fvisibility=hidden`, so this behavior is intentional - **I'm not sure why `libavcodec_plugin.so` is taking offense however, this should work fine**. In the case of the other mentioned issue, it was a conflict in global-static variable storage.

My next line of investigation will be attempting to create a compatible `libffmpeg.so` from the standard distro-supplied ffmpeg libs (it's an amalgamation of what should be at least `libavcodec.so` and `libavformat.so`), but that'll probably be many moons away - pinning my Linux release to 0.36.7 is still holding out for me, but steadily getting more painful.

**Comment by jayke-vbh** [comment]
Thanks for acknowledging this is still an issue. For the moment this is preventing me to use this as a solution, while it seems well suited otherwise.

Is there anyway I can help by performing tests or looking into things? I'm not very experienced with linking of libraries and stuff, but maybe I can do something. Otherwise, I would be willing to offer a bounty, if that would help prioritize this issue for you guys?

**Comment by RSATom** [comment]
> Is there anyway I can help by performing tests or looking into things?
Unfortunately no, it's require C/C++ software debugging/bugfixing skills to get it solved...

> Otherwise, I would be willing to offer a bounty, if that would help prioritize this issue for you guys?

It's already number 1 issue in my priority list, I just don't have free time atm.

**Comment by RSATom** [comment]
I think problem is really come from `libffmpeg.so` from Electron. I've tried preload this `libffmpeg.so` to [QmlVlcDemo](https://github.com/RSATom/QmlVlcDemo) with LD_PRELOAD and got the same problem with `.avi` playback. So I think problem is really with exports with same name in different `.so` modules.

All possible solution I can imagine at the moment are pretty complex:
1. Rebuid `Electron` without media playback support (i.e. without `libffmpeg.so`) or with `libffmpeg` statically linked to Electron module (as it was before `Electron v0.36.8`)
2. Implement import table replacement at runtime: https://www.apriorit.com/dev-blog/181-elf-hook (same in Russian: https://habrahabr.ru/post/106107/)

**Comment by RSATom** [comment]
I think second option will be better solution, but unfortunately it will take pretty huge amount of time to implement it, I don't have atm... So help wanted...

**Comment by MikeGCV** [comment]
The issue with the latest builds of electron in linux is solved?

**Comment by RSATom** [comment]
@MikeGCV, I didn't solve it. Maybe something was changed on Electron side, I didn't check.

**Comment by amilajack** [comment]
Has this changed with the current modern versions of electron?

**Comment by RSATom** [comment]
@amilajack, it builds without problem, but didn't run due to conflict with ffmpeg bundled with Electron.

**Comment by RSATom** [comment]
but I didn't try latest versions.

**Comment by amilajack** [comment]
I see. How can I try this out myself?

**Comment by RSATom** [comment]
@amilajack, Just try https://github.com/RSATom/wcjs-ugly-demo with with `WebChimera.js`  built against latest `Electron`

**Comment by amilajack** [comment]
Just made a repo to test this out:

https://github.com/amilajack/wcjs-example

The problem is that electron exits with no errors. Do you know the reason for this?

**Comment by RSATom** [comment]
Don't see any issue in your code, but I didn't try run it. Maybe it's the problem with Electron. Try the same with older Electron(it's 100% worked with Electron v0.33.9).

**Comment by amilajack** [comment]
Tried the demo and it works 100%. When changing the version to the latest electron version, it fails to render any video at at all.

**Comment by amilajack** [comment]
Possible solution: compile vlc to WebAssembly or asm.js with emscripten?

**Comment by RSATom** [comment]
> Tried the demo and it works 100%. When changing the version to the latest electron version, it fails to render any video at at all.
So problem is still persists. I'm not surprised.

> Possible solution: compile vlc to WebAssembly or asm.js with emscripten?

You could try, if you are brave enough. On my side, I don't think it's possible to do by any single man.

**Comment by amilajack** [comment]
https://github.com/mbebenita/Broadway/

This was already done. It only supports mp4 tho

**Comment by RSATom** [comment]
It's not the same as VLC

**Comment by amilajack** [comment]
Yea that's true. What do you think about starting a new project that compiles vlc to WebAssembly to support new versions of electron/nwjs?

**Comment by RSATom** [comment]
I think I will die before it will be finished. It will require **huge** amount of work.

**Comment by RSATom** [comment]
Read this: https://github.com/RSATom/WebChimera.js/issues/69#issuecomment-222287080
I don't see any other real solutions.

**Comment by amilajack** [comment]
Hmm. What about reviving the fire breath based plugin and migrating it to PNaCl?

**Comment by RSATom** [comment]
it's hard too since there are no libvlc for PNaCL

**Comment by jayke-vbh** [comment]
@amilajack one 'dirty hack' I've found is to replace the `libffmpeg.so` in your electron build (for electron-prebuilt it's in `node_modules/electron_prebuilt/dist/`) with one that does have the right codecs. Finding the correct one is difficult though. There's one in `nw.js` and in their documentation there's instructions on how to compile with non-free codecs. There's also a few to be found in the Chromium sources I think. 

Non of these gave me the full capabilities in video playback though, best result was full playback but no subs or something like that. (I eventually moved to transparent electron with mpv underneath, controlled through unix socket, but that's only an option when you have control over the entire system, not if you just ship your app).

PS note that by replacing your libffmpeg.so to contain non-free codecs you might be legally required to pay royalty fees.

**Comment by amilajack** [comment]
@jayke-vbh in my `node_modules/electron-prebuilt/dist`, all i have is:

```
drwxr-xr-x   6 amila  staff   204B Jul 19 23:03 .
drwxr-xr-x  15 amila  staff   510B Jul 19 23:03 ..
drwxr-xr-x   3 amila  staff   102B Jul 19 23:03 Electron.app
-rw-r--r--   1 amila  staff   1.0K Jul 19 23:03 LICENSE
-rw-r--r--   1 amila  staff   1.2M Jul 19 23:03 LICENSES.chromium.html
-rw-r--r--   1 amila  staff     6B Jul 19 23:03 version
```

**Comment by jayke-vbh** [comment]
Hmm don't know about that. Maybe it's different because you install electron-prebuilt with -g (according to your repo). Try to search the system for libffmpeg.so maybe?

**Comment by amilajack** [comment]
Actually I have a local installation and dont have a global one. My electron-prebuilt version is the latest one btw. Not sure if that helps.

**Comment by jaruba** [comment]
Sounds like you two are talking about different versions of electron..

**Comment by jayke-vbh** [comment]
Nope, grabbed the latest just to be sure:

```
jayke@stb-6i7:~/tmp/node_modules/electron-prebuilt/dist$ ls -l
total 108496
-rw-r--r-- 1 jayke jayke  9692136 Jul 20 13:09 content_shell.pak
-rwxr-xr-x 1 jayke jayke 66108872 Jul 20 13:09 electron
-rw-r--r-- 1 jayke jayke 10127152 Jul 20 13:09 icudtl.dat
-rw-r--r-- 1 jayke jayke  2578936 Jul 20 13:09 libffmpeg.so
-rwxr-xr-x 1 jayke jayke 20208104 Jul 20 13:09 libnode.so
-rw-r--r-- 1 jayke jayke     1055 Jul 20 13:09 LICENSE
-rw-r--r-- 1 jayke jayke  1276221 Jul 20 13:09 LICENSES.chromium.html
drwxrwxr-x 2 jayke jayke     4096 Jul 20 13:09 locales
-rw-r--r-- 1 jayke jayke   415533 Jul 20 13:09 natives_blob.bin
drwxrwxr-x 2 jayke jayke     4096 Jul 20 13:09 resources
-rw-r--r-- 1 jayke jayke   661620 Jul 20 13:09 snapshot_blob.bin
-rw-r--r-- 1 jayke jayke        6 Jul 20 13:09 version
jayke@stb-6i7:~/tmp/node_modules/electron-prebuilt/dist$ cat version
v1.2.7
```

Isn't `.app` a osx thing? Did you get electron-prebuilt through `npm install electron-prebuilt`?

**Comment by jaruba** [comment]
@jayke-vbh `.app` is not only a OSX thing, it's actually a folder.. but yeah, your right, it looks like he's using Electron for OSX..

**Comment by amilajack** [comment]
> Did you get electron-prebuilt through npm install electron-prebuilt
Here's the steps I followed:

```bash
mkdir test
cd test
npm init -y
npm i --save electron-prebuilt
```

**Comment by jayke-vbh** [comment]
Doing exactly the same gives me the version I showed above. Probably a OS or npm configuraration difference? I've tried this on Debian (but about a month ago) and now Ubuntu, same result.

**Comment by jaruba** [comment]
@amilajack try deleting your npm cache

**Comment by amilajack** [comment]
My npm version is `3.10.5`. Not sure if that helps.

**Comment by amilajack** [comment]
@jaruba ahh good idea!

**Comment by amilajack** [comment]
Shit. No luck

**Comment by amilajack** [comment]
@jayke-vbh I just tried this on linux and I can see the `libffmpeg.so` file! What are the steps that I have to do after this?

**Comment by jayke-vbh** [comment]
Find an alternative `libffmpeg.so` that does have the required codecs, and replace it with that. Some alternatives I've found came from the Chrome repositories I think, from NW.js and I think one of the others in my project managed to get one from Butter. NW.js also has instruction on how to compile your own, but you might need to play around with some of the  configuration files to get the right codecs and features for your project: http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/

**Comment by amilajack** [comment]
And the same `libffmpeg.so` will work on Mac, linux, windows?

**Comment by jayke-vbh** [comment]
Definitely not, as `.so` is Linux specific. In Windows there's probably a `dll` somewhere, and in Mac I assume a different one again.

But as far as I understand, this issue is limited to Linux Electron anyway, so that shouldn't be a problem?

**Comment by amilajack** [comment]
Will this cause a problem with linking paths (if that's what they're called)?

**Comment by amilajack** [comment]
After building `butter`, I've a `.so` file called `ffmpegsumo.so` on osx. What can be done with this?

**Comment by jayke-vbh** [comment]
That's the one we found as well, just rename it to libffmpeg.so. I think with that one we had the issue that there's no h.265/HEVC support though.

Not sure about the other stuff, but as the filename stays exactly the same it shouldn't change anything. Don't know what would happen if you package it into a prebuilt app though.

**Comment by lyssdod** [comment]
What's the status of this? Is it still impossible to use WebChimera with latest versions of electron on Linux?

**Comment by jordansteeves** [comment]
Yeah, the current version of WebChimera is using an electron release from Oct 16, 2015. That's almost an entire year behind! 😢

**Comment by RSATom** [comment]
Yea, it's still broken. Patch welcome...

**Comment by amilajack** [comment]
@lyssdod @jordansteeves just follow @jayke-vbh's advice

**Comment by lyssdod** [comment]
Well, it builds without any errors, have to try it in the app

**Comment by lyssdod** [comment]
@RSATom, I think I've found out why this happens:

1. While building via Travis you're using `libvlc-dev` for Linux (https://github.com/RSATom/WebChimera.js/blob/master/.travis.yml#L30) and prebuilt VLC for OSX (https://github.com/RSATom/WebChimera.js/blob/master/travis_before_install.sh)
2. This prebuilt stuff is already linked to system's default ffmpeg
3. Your wrapper links to it -> it links to default system libs
4. Compiled node extension is also linked against system vlc (Gentoo):

```
/tmp/test/WebChimera.js$ ./build_electron.sh
[snip]
/tmp/test/WebChimera.js/build/Release $ lddtree WebChimera.js.node 
WebChimera.js.node => ./WebChimera.js.node (interpreter => none)
    libvlc.so.5 => /usr/lib64/libvlc.so.5
        libvlccore.so.8 => /usr/lib64/libvlccore.so.8
            librt.so.1 => /lib64/librt.so.1
            libidn.so.11 => /usr/lib64/libidn.so.11
            libdl.so.2 => /lib64/libdl.so.2
                ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
            libdbus-1.so.3 => /usr/lib64/libdbus-1.so.3
        libpthread.so.0 => /lib64/libpthread.so.0
    libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
    libm.so.6 => /lib64/libm.so.6
    libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libgcc_s.so.1
    libc.so.6 => /lib64/libc.so.6
```
It does not indicate ffmpeg here, but I'm assuming it does dlopen or something like that since ffmpeg is required dependency: https://wiki.videolan.org/Contrib_Status/#Usage

In the extension I develop currently (node-libtorrent-ng) I've had a similar issue, I had to use a third-party library (libtorrent) which's dependent on boost and always resolved to local system's boost. I ended up compiling everything as static (both libtorrent and boost) and linking into the addon; this way I managed to do a truly redistributable library (depends only on libstdc++) with acceptable size (about 4Mbs, even lesser than boost + libtorrent compiled as dynamic!). 

My ideas are:

1. Use recent (or not) libvlc, and compile it as static;
2. In case of compiling against electron, link explicitly to its ffmpeg (-L<electron dir>), though it may involve some play with `rpath` for Mac;
3. Bundle everything into your addon, thus making it independent on system libs (no need to install VLC) and redistributable.

What do you think?

**Comment by RSATom** [comment]
The problem is it's not so easy build libvlc as static library

**Comment by lyssdod** [comment]
I will try to do it. Also, there's kind of official cpp wrapper: https://code.videolan.org/videolan/libvlcpp/tree/master

**Comment by TomBZombie** [comment]
Is this something that could be more easily fixed electron's end or does it have to  be fixed here?

**Comment by RSATom** [comment]
if you can rebuild Electron - yes, you could change Electron's build configuration to link ffmpeg statically.

**Comment by kazemihabib** [comment]
@RSATom  , @lyssdod 
hi, I found a way to fix the problem in arch linux with help of https://github.com/tensor5/arch-atom/tree/master/electron .
In arch linux the package of atom in official repository not uses the embeded electron , it installs the electron package first then uses that .
in the link above as you see they write patches for static library , use system ffmpeg and ... .
so if you use arch linux electron package and webchimera it will work (I tried it works :) )
with those patches and rebuild electron will fix the problem in other linux distributions too.

**Comment by thesabbir** [comment]
can anybody fix this or let us know how to?

**Comment by RSATom** [comment]
@thesabbir, I think the simplest solution will be rebuild electron with patches mentioned by @kazemihabib

**Comment by sunxfancy** [comment]
@RSATom Any update? Is there a way to build customized libffmpeg.so to replace the default one?

**Comment by RSATom** [comment]
@sunxfancy, no. I didn't work on this issue.

> Is there a way to build customized libffmpeg.so to replace the default one?

You don't need rebuild libffmpeg.so, you need rebuild Electron with static libffmpeg. And no, I didn't investigate how to do it yet.

**Comment by Kagami** [comment]
Simplest workaround that I use for mpv.js/boram is:

```
gcc -shared -lavformat -o node_modules/electron/dist/libffmpeg.so
```

It's unfortunately broken since 1.4.15: https://github.com/electron/libchromiumcontent/issues/268

**Comment by Kagami** [comment]
Also found workaround for latest Electron! See https://github.com/Kagami/mpv.js/issues/10#issuecomment-285829027

**Comment by RSATom** [comment]
@Kagami, is it use sandboxed libmpv?

**Comment by Kagami** [comment]
No, the system one.

**Comment by RSATom** [comment]
hm... so pepper plugins could be run in not sandboxed environment? Interesting

**Comment by Kagami** [comment]
Yes. It's kinda intended for dev purposes, but nothing prevents you to use in production :) (Well, there are few pitfalls, but not critical.)

**Comment by vishal733** [comment]
I'm planning to try WebChimera.js on latest electron version: (v1.7.6). Seems there's a lot to try to get it to work. And seems quite involved.
Just one question. WebChimera.js doesn't require any NSAPI support on chrome side, right? Since that's already been removed from Chrome.

**Comment by RSATom** [comment]
@vishal733, no, WebChimera.js doesn't require NSAPI. It's based on Node.js addons API.

**Comment by RSATom** [comment]
Closed as too old.
